const content_review = document.getElementById("review_test");

fetch("/data/data.json").then(response => response.json()).then(data =>{
    content_review.innerHTML += "<div class='col-sm-4'></div>" 

    +" <div class='col-sm-4' id= 'Sticky'>"
    +" <span class='top10'>Top <span style='color:red;'>5</span> most delicious cakes</span>" +
    "<div><a href='#No1'>1. Ormari sed consequat for birthday</a></div>"
    + "<div><a href ='#No2'>2. Ormari sed consequat for Marriage with Egg </a></div>"
    +"<div><a href ='#No3'>3. Ormari sed consequat for Anniversary with Egg </a></div>"
    +"<div><a href ='#No4'>4. Ormari sed consequat for gallsery with Egg </a></div>"
    +"<div><a href ='#No5'>5. Ormari sed consequat for sale with Egg </a></div>"
    +"</div>"

    +"<div class='col-sm-7'>"
    +"<div id='No1'>"
    +"<img class='img_review' src ='https://toplist.vn/images/numbers/1.svg'>"
    +"<a class='Name_product' href='blog.html'>Ormari sed consequat for birthday</a>"
    +"<div><span style='font-weight: bold;'>Ormari sed consequat: </span>"
    +"<span class='putOutJson'></span></div>"
    +"<div style='margin-top: 20px;'><span class='Lien_he'>CONTACT INFORMATION: </span></div>"
    +"<div><span class='Lien_he'>Address: </div>"
    +"<div><ul><li>590 Đ. Cách Mạng Tháng 8, Phường 11, Quận 3, Thành phố Hồ Chí Minh 723564, Vietnam</li></ul></div>"
    +"<div><span class='Lien_he'>Hotline: </span> +111 222-3333 Or +456 786-7890</div>"
    +"<div><span class='Lien_he'>Email:</span></div>"
    +"<div><ul><li>Shaikhfarhan@Gmail.Com</li>"
    +"<li>Xyzemail@Gmail.Com</li></ul></div>"
    +"<div style='margin-top: 20px' ><img class='hinh' src= '/images/img-birthday/birthday-3.jpg'></div>"
    +"<div style='margin-top: 20px' ><img class='hinh' src= '/images/img-birthday/birthday-1.jpg'></div>"
    +"</div>"

    +"<div id='No2' style='margin-top:80px;'>"
    +"<img class='img_review' src ='https://toplist.vn/images/numbers/2.svg'>"
    +"<a class='Name_product' href='blog.html'>Ormari sed consequat for Marriage With Egg</a>"
    +"<div><span style='font-weight: bold;'>Ormari sed consequat: </span>"
    +"<span class='putOutJson'></span></div>"
    +"<div style='margin-top: 20px;'><span class='Lien_he'>CONTACT INFORMATION: </span></div>"
    +"<div><span class='Lien_he'>Address: </div>"
    +"<div><ul><li>590 Đ. Cách Mạng Tháng 8, Phường 11, Quận 3, Thành phố Hồ Chí Minh 723564, Vietnam</li></ul></div>"
    +"<div><span class='Lien_he'>Hotline: </span> +111 222-3333 Or +456 786-7890</div>"
    +"<div><span class='Lien_he'>Email:</span></div>"
    +"<div><ul><li>Shaikhfarhan@Gmail.Com</li>"
    +"<li>Xyzemail@Gmail.Com</li></ul></div>"
    +"<div style='margin-top: 20px' ><img class='hinh' src= '/images/wedding-img/wedding-cake-3.jpg'></div>"
    +"<div style='margin-top: 20px' ><img class='hinh' src= '/images/wedding-img/wedding-cake-5.jpg'></div>"
    +"</div>"

    +"<div id='No3' style='margin-top:80px;'>"
    +"<img class='img_review' src ='https://toplist.vn/images/numbers/3.svg'>"
    +"<a class='Name_product' href='blog.html'>Ormari sed consequat for Marriage With Egg</a>"
    +"<div><span style='font-weight: bold;'>Ormari sed consequat: </span>"
    +"<span class='putOutJson'></span></div>"
    +"<div style='margin-top: 20px;'><span class='Lien_he'>CONTACT INFORMATION: </span></div>"
    +"<div><span class='Lien_he'>Address: </div>"
    +"<div><ul><li>590 Đ. Cách Mạng Tháng 8, Phường 11, Quận 3, Thành phố Hồ Chí Minh 723564, Vietnam</li></ul></div>"
    +"<div><span class='Lien_he'>Hotline: </span> +111 222-3333 Or +456 786-7890</div>"
    +"<div><span class='Lien_he'>Email:</span></div>"
    +"<div><ul><li>Shaikhfarhan@Gmail.Com</li>"
    +"<li>Xyzemail@Gmail.Com</li></ul></div>"
    +"<div style='margin-top: 20px' ><img class='hinh' src= '/images/Anniversary-img/product-4.jpg'></div>"
    +"<div style='margin-top: 20px' ><img class='hinh' src= '/images/Anniversary-img/product-8.jpg'></div>"
    +"</div>"

    +"<div id='No4' style='margin-top:80px;'>"
    +"<img class='img_review' src ='https://toplist.vn/images/numbers/4.svg'>"
    +"<a class='Name_product' href='blog.html'>Ormari sed consequat for Marriage With Egg</a>"
    +"<div><span style='font-weight: bold;'>Ormari sed consequat: </span>"
    +"<span class='putOutJson'></span></div>"
    +"<div style='margin-top: 20px;'><span class='Lien_he'>CONTACT INFORMATION: </span></div>"
    +"<div><span class='Lien_he'>Address: </div>"
    +"<div><ul><li>590 Đ. Cách Mạng Tháng 8, Phường 11, Quận 3, Thành phố Hồ Chí Minh 723564, Vietnam</li></ul></div>"
    +"<div><span class='Lien_he'>Hotline: </span> +111 222-3333 Or +456 786-7890</div>"
    +"<div><span class='Lien_he'>Email:</span></div>"
    +"<div><ul><li>Shaikhfarhan@Gmail.Com</li>"
    +"<li>Xyzemail@Gmail.Com</li></ul></div>"
    +"<div style='margin-top: 20px' ><img class='hinh' src= '/images/gallery/gallery-img-4.jpg'></div>"
    +"<div style='margin-top: 20px' ><img class='hinh' src= '/images/gallery/gallery-img-6.jpg'></div>"
    +"</div>"

    +"<div id='No5' style='margin-top:80px;'>"
    +"<img class='img_review' src ='https://toplist.vn/images/numbers/5.svg'>"
    +"<a class='Name_product' href='blog.html'>Ormari sed consequat for Marriage With Egg</a>"
    +"<div><span style='font-weight: bold;'>Ormari sed consequat: </span>"
    +"<span class='putOutJson'></span></div>"
    +"<div style='margin-top: 20px;'><span class='Lien_he'>CONTACT INFORMATION: </span></div>"
    +"<div><span class='Lien_he'>Address: </div>"
    +"<div><ul><li>590 Đ. Cách Mạng Tháng 8, Phường 11, Quận 3, Thành phố Hồ Chí Minh 723564, Vietnam</li></ul></div>"
    +"<div><span class='Lien_he'>Hotline: </span> +111 222-3333 Or +456 786-7890</div>"
    +"<div><span class='Lien_he'>Email:</span></div>"
    +"<div><ul><li>Shaikhfarhan@Gmail.Com</li>"
    +"<li>Xyzemail@Gmail.Com</li></ul></div>"
    +"<div style='margin-top: 20px' ><img class='hinh' src= '/images/home12.png'></div>"
    +"<div style='margin-top: 20px' ><img class='hinh' src= '/images/cat-1.jpg'></div>"
    +"</div>"
    +"</div>"

    for(var i =0 ;i <data.details.length;i ++){
        document.getElementsByClassName("putOutJson")[i].innerHTML = data.details[i].descript.describe;
    }
})
